"""
Recommendation engine based on configurable screening protocol.
Maps AI screening outputs to clinical next-step recommendations.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# Configurable protocol-based recommendations
# In production, these would be reviewed and approved by qualified ROP specialists
SCREENING_PROTOCOL = {
    "Normal": {
        "recommendation": (
            "Routine follow-up screening as per institutional protocol. "
            "Continue standard postnatal screening schedule."
        ),
        "recommendation_ta": (
            "நிறுவன நெறிமுறையின்படி வழக்கமான பின்தொடர்தல் பரிசோதனை. "
            "நிலையான பிறப்புக்குப் பின் பரிசோதனை அட்டவணையைத் தொடரவும்."
        ),
        "urgency": "routine",
        "color": "green",
    },
    "Pre-Plus/Mild": {
        "recommendation": (
            "Increased monitoring recommended. Schedule follow-up screening within 1–2 weeks. "
            "Specialist ophthalmological review is advised to confirm findings."
        ),
        "recommendation_ta": (
            "அதிகரிக்கப்பட்ட கண்காணிப்பு பரிந்துரைக்கப்படுகிறது. 1–2 வாரங்களுக்குள் "
            "பின்தொடர்தல் பரிசோதனையை திட்டமிடவும். கண்டுபிடிப்புகளை உறுதிப்படுத்த "
            "நிபுணர் கண் மருத்துவ மதிப்பாய்வு அறிவுறுத்தப்படுகிறது."
        ),
        "urgency": "elevated",
        "color": "yellow",
    },
    "Plus Disease/Severe": {
        "recommendation": (
            "⚠️ URGENT: Findings suggest possible severe ROP. "
            "Immediate specialist referral is strongly recommended. "
            "Prompt ophthalmological evaluation is essential to determine "
            "if treatment intervention is needed."
        ),
        "recommendation_ta": (
            "⚠️ அவசரம்: கண்டுபிடிப்புகள் கடுமையான ROP சாத்தியத்தை சுட்டிக்காட்டுகின்றன. "
            "உடனடி நிபுணர் பரிந்துரை வலுவாக பரிந்துரைக்கப்படுகிறது. "
            "சிகிச்சை தலையீடு தேவையா என்பதை தீர்மானிக்க உடனடி கண் மருத்துவ "
            "மதிப்பீடு அவசியம்."
        ),
        "urgency": "urgent",
        "color": "red",
    },
    "UNGRADABLE": {
        "recommendation": (
            "The retinal image could not be assessed by the AI model. "
            "Please recapture the image with better quality or arrange for "
            "manual expert review by a qualified ophthalmologist."
        ),
        "recommendation_ta": (
            "AI மாதிரியால் விழித்திரை படத்தை மதிப்பீடு செய்ய இயலவில்லை. "
            "சிறந்த தரத்தில் படத்தை மீண்டும் எடுக்கவும் அல்லது தகுதியான "
            "கண் மருத்துவரிடம் கைமுறை நிபுணர் மதிப்பாய்வுக்கு ஏற்பாடு செய்யவும்."
        ),
        "urgency": "review",
        "color": "gray",
    },
    "DEMO": {
        "recommendation": (
            "⚠️ DEMO MODE: This is a demonstration result generated without a trained AI model. "
            "It has NO clinical validity and must NOT be used for any medical decision. "
            "To enable real screening, install a validated ROP model."
        ),
        "recommendation_ta": (
            "⚠️ செயல்விளக்க பயன்முறை: இது பயிற்சி பெற்ற AI மாதிரி இல்லாமல் "
            "உருவாக்கப்பட்ட செயல்விளக்க முடிவு. இதற்கு மருத்துவ செல்லுபடியாகும் தன்மை "
            "இல்லை, எந்த மருத்துவ முடிவுக்கும் பயன்படுத்தக்கூடாது."
        ),
        "urgency": "demo",
        "color": "orange",
    },
    "FAILED": {
        "recommendation": (
            "AI analysis could not be completed due to a technical error. "
            "Manual specialist review is required."
        ),
        "recommendation_ta": (
            "தொழில்நுட்ப பிழையின் காரணமாக AI பகுப்பாய்வை நிறைவு செய்ய இயலவில்லை. "
            "கைமுறை நிபுணர் மதிப்பாய்வு தேவை."
        ),
        "urgency": "review",
        "color": "gray",
    },
}

DISCLAIMER = (
    "This screening result is generated by an AI-assisted research prototype. "
    "It does NOT constitute a confirmed medical diagnosis. "
    "All findings must be verified by a qualified ophthalmologist. "
    "This application supports healthcare professionals and does not replace specialist examination."
)

DISCLAIMER_TA = (
    "இந்த பரிசோதனை முடிவு AI-உதவி ஆராய்ச்சி முன்மாதிரியால் உருவாக்கப்பட்டது. "
    "இது உறுதிசெய்யப்பட்ட மருத்துவ நோயறிதல் அல்ல. "
    "அனைத்து கண்டுபிடிப்புகளும் தகுதியான கண் மருத்துவரால் சரிபார்க்கப்பட வேண்டும். "
    "இந்த பயன்பாடு சுகாதார நிபுணர்களை ஆதரிக்கிறது, நிபுணர் பரிசோதனையை மாற்றாது."
)


def get_recommendation(classification: str, status: str, language: str = "en") -> dict:
    """
    Get protocol-based recommendation for a screening result.
    Never recommends treatment or medication directly.
    """
    # Determine which protocol entry to use
    if status == "demo":
        key = "DEMO"
    elif status == "failed":
        key = "FAILED"
    elif classification in SCREENING_PROTOCOL:
        key = classification
    else:
        key = "UNGRADABLE"

    protocol = SCREENING_PROTOCOL[key]
    is_tamil = language == "ta"

    return {
        "recommendation": protocol["recommendation_ta"] if is_tamil else protocol["recommendation"],
        "urgency": protocol["urgency"],
        "color": protocol["color"],
        "disclaimer": DISCLAIMER_TA if is_tamil else DISCLAIMER,
    }


def determine_clinical_status(
    quality_status: Optional[str],
    classification: Optional[str],
    confidence: Optional[float],
    is_demo: bool = False,
    language: str = "en",
) -> dict:
    """
    Synthesizes image quality, model output, and clinical rules into standard labels:
    - ROP DETECTED / SCREEN POSITIVE
    - NO ROP DETECTED / SCREEN NEGATIVE
    - INCONCLUSIVE / UNGRADABLE – REPEAT IMAGING OR REFER

    Clinical Safety Invariant:
    A low-quality or ungradable image must NEVER produce a misleading negative result.
    """
    is_ta = language == "ta"
    quality_upper = (quality_status or "UNGRADABLE").upper()
    
    # Map quality to standard labels: GOOD, POOR, UNGRADABLE
    if quality_upper in ["ACCEPTABLE", "GOOD"]:
        quality_display = "GOOD"
    elif quality_upper == "POOR":
        quality_display = "POOR"
    else:
        quality_display = "UNGRADABLE"

    # Case 1: Image is ungradable
    if quality_display == "UNGRADABLE":
        canonical_status = (
            "முடிவற்றது / தரம் குறைந்த படம் – மீண்டும் படம் எடுக்கவும் அல்லது பரிந்துரைக்கவும்"
            if is_ta else "INCONCLUSIVE / UNGRADABLE – REPEAT IMAGING OR REFER"
        )
        rec = get_recommendation("UNGRADABLE", "ungradable", language)
        return {
            "canonical_status": canonical_status,
            "severity": "Ungradable" if not is_ta else "மதிப்பிட முடியாதது",
            "plus_disease_status": "Ungradable" if not is_ta else "மதிப்பிட முடியாதது",
            "quality_display": quality_display,
            "confidence_display": None,
            "recommendation": rec["recommendation"],
            "urgency": "review",
            "color": "gray",
            "disclaimer": rec["disclaimer"],
        }

    # Case 2: Demo Mode (No real trained model weights installed)
    if is_demo:
        canonical_status = (
            "செயல்விளக்க முடிவு (மாதிரி ஏற்றப்படவில்லை)"
            if is_ta else "DEMO / SIMULATED RESULT – NO VALIDATED MODEL"
        )
        rec = get_recommendation("DEMO", "demo", language)
        return {
            "canonical_status": canonical_status,
            "severity": "Demonstration Only" if not is_ta else "செயல்விளக்கம் மட்டுமே",
            "plus_disease_status": "Unverified (Demo)" if not is_ta else "சரிபார்க்கப்படவில்லை",
            "quality_display": quality_display,
            "confidence_display": None,
            "recommendation": rec["recommendation"],
            "urgency": "demo",
            "color": "orange",
            "disclaimer": rec["disclaimer"],
        }

    # Case 3: Real Model Inference
    # Safeguard: If image quality is POOR and classification is Normal, or confidence < 0.65
    # it must NOT be signed off as Screen Negative!
    if quality_display == "POOR" and (not classification or "normal" in classification.lower() or (confidence is not None and confidence < 0.65)):
        canonical_status = (
            "முடிவற்றது / தரம் குறைந்த படம் – மீண்டும் படம் எடுக்கவும் அல்லது பரிந்துரைக்கவும்"
            if is_ta else "INCONCLUSIVE / UNGRADABLE – REPEAT IMAGING OR REFER"
        )
        rec = {
            "recommendation": (
                "படத்தின் தரம் குறைவாக உள்ளது. குறைபாடுள்ள படத்தில் எதிர்மறை முடிவை பாதுகாப்பாக உறுதிப்படுத்த முடியாது. மீண்டும் படம் எடுக்கவும் அல்லது தகுதியான கண் மருத்துவரிடம் பரிசோதிக்கவும்."
                if is_ta else
                "Image quality is poor. A negative screening cannot be safely determined on degraded imagery. Recapture retinal image or refer for qualified ophthalmologist direct examination."
            ),
            "urgency": "review",
            "color": "yellow",
            "disclaimer": DISCLAIMER_TA if is_ta else DISCLAIMER,
        }
        return {
            "canonical_status": canonical_status,
            "severity": "Inconclusive (Degraded Image)" if not is_ta else "முடிவற்றது (குறைந்த தரம்)",
            "plus_disease_status": "Indeterminate" if not is_ta else "நிர்ணயிக்கப்படவில்லை",
            "quality_display": quality_display,
            "confidence_display": f"{confidence * 100:.1f}%" if confidence is not None else None,
            "recommendation": rec["recommendation"],
            "urgency": rec["urgency"],
            "color": rec["color"],
            "disclaimer": rec["disclaimer"],
        }

    # If classification contains Plus Disease / Severe
    if classification and ("plus disease" in classification.lower() or "severe" in classification.lower()):
        canonical_status = (
            "ROP கண்டறியப்பட்டது / நேர்மறை பரிசோதனை"
            if is_ta else "ROP DETECTED / SCREEN POSITIVE"
        )
        rec = get_recommendation("Plus Disease/Severe", "completed", language)
        return {
            "canonical_status": canonical_status,
            "severity": "Plus Disease / Severe ROP" if not is_ta else "கடுமையான ROP / பிளஸ் நோய்",
            "plus_disease_status": "Plus Disease Detected" if not is_ta else "பிளஸ் நோய் கண்டறியப்பட்டது",
            "quality_display": quality_display,
            "confidence_display": f"{confidence * 100:.1f}%" if confidence is not None else None,
            "recommendation": rec["recommendation"],
            "urgency": "urgent",
            "color": "red",
            "disclaimer": rec["disclaimer"],
        }

    # If classification contains Pre-Plus / Mild
    if classification and ("pre-plus" in classification.lower() or "mild" in classification.lower()):
        canonical_status = (
            "ROP கண்டறியப்பட்டது / நேர்மறை பரிசோதனை"
            if is_ta else "ROP DETECTED / SCREEN POSITIVE"
        )
        rec = get_recommendation("Pre-Plus/Mild", "completed", language)
        return {
            "canonical_status": canonical_status,
            "severity": "Pre-Plus / Mild ROP" if not is_ta else "லேசான ROP / ப்ரீ-பிளஸ்",
            "plus_disease_status": "Pre-Plus Suspected" if not is_ta else "ப்ரீ-பிளஸ் சந்தேகம்",
            "quality_display": quality_display,
            "confidence_display": f"{confidence * 100:.1f}%" if confidence is not None else None,
            "recommendation": rec["recommendation"],
            "urgency": "elevated",
            "color": "yellow",
            "disclaimer": rec["disclaimer"],
        }

    # Normal classification on GOOD/ACCEPTABLE image
    canonical_status = (
        "ROP கண்டறியப்படவில்லை / எதிர்மறை பரிசோதனை"
        if is_ta else "NO ROP DETECTED / SCREEN NEGATIVE"
    )
    rec = get_recommendation("Normal", "completed", language)
    return {
        "canonical_status": canonical_status,
        "severity": "No Signs of ROP" if not is_ta else "ROP அறிகுறிகள் இல்லை",
        "plus_disease_status": "Not Detected" if not is_ta else "கண்டறியப்படவில்லை",
        "quality_display": quality_display,
        "confidence_display": f"{confidence * 100:.1f}%" if confidence is not None else None,
        "recommendation": rec["recommendation"],
        "urgency": "routine",
        "color": "green",
        "disclaimer": rec["disclaimer"],
    }
